### ISSUE TITLE
Allow firefly to support multiple functions

### ISSUE THREAD

**Issue by anandology** [rorodata/firefly#10]
It should take multiple functions as command line arguments and expose all of them.

```
$ firefly myfile.square myfile.cube
```
And use:

```
$ curl -d '{"x": 5}' http://localhost:8000/square
25
$ curl -d '{"x": 5}' http://localhost:8000/cube
125
```

**Comment by palnabarun** [comment]
This can be a plan: For addition of all routes, there would be a generate_routes function in main.py which will take list of function names and all routes to the app. It would not add / because / would be configured from now onwards with every Firefly instance. More on that below.

**Comment by anandology** [comment]
It might be better to have a `add_functions` method in Firefly and let that take a list of function names. That way the hard work is pushed to Firefly instead of keeping it main. What do you think @palnabarun?

**Comment by palnabarun** [comment]
That means removal of add_route and introduction of add_functions in main.py. Right?

**Comment by anandology** [comment]
What I suggested doesn't look like a good idea when I think again.

Just go with calling add_route from main.

**Comment by palnabarun** [comment]
Okay. Will start the implementation.
