### ISSUE TITLE
Use flit for packing firefly

### ISSUE THREAD

**Issue by anandology** [rorodata/firefly#46]
[flit][] is the upcoming Python standard for distributing python packages. You just write a simple config file with the package metadata and not have to worry about setup.py and other mess.

[flit]: https://github.com/takluyver/flit

**Comment by palnabarun** [comment]
We can use this configuration for `flit.ini`:

```
[metadata]
module = firefly
author = rorodata
author-email = rorodata.team@gmail.com
home-page = https://firefly-python.readthedocs.io
description = Readme.rst
requires = gunicorn==19.7.1,
    WebOb==1.7.2,
    requests==2.18.1,
    PyYAML==3.12,
    funcsigs==1.0.2; python_version < '3'

[scripts]
firefly = firefly.app:main
```

The only thing I'm skeptical about is the absence of specifying version.

Also, `flit` documentation says description should be in `rst` format. So, `firefly` should be converted to `rst` format.

**Comment by anandology** [comment]
Flit is causing more pain. It is not possible to install a package from git if it is using flit. I would like to continue using setuptools.
