### ISSUE TITLE
Add support for returning a file object from a function

### ISSUE THREAD

**Issue by anandology** [rorodata/firefly#47]
Now that we have support for sending files to a firefly function, the next thing is to receive a file from function.

**Comment by palnabarun** [comment]
I was already working on this through #37

**Comment by anandology** [comment]
We had an urgent requirement for this and I've already implemented it. @palnabarun please bear with me this time.

**Comment by palnabarun** [comment]
Woah. That was fast. :+1:  :open_mouth:
