### ISSUE TITLE
client sends POST request after a GET request

### ISSUE THREAD

**Issue by sohail535** [rorodata/firefly#48]
![image](https://user-images.githubusercontent.com/8740782/28972814-c10ce65e-794e-11e7-90b6-66bebe69cd0e.png)

Looks like every `GET` request is followed by a `POST` request.

Is this expected?

**Comment by palnabarun** [comment]
Yes. This is because whenever a function is called on the client it instantiates a `RemoteFunction` Object which in turn calls the `/` endpoint for function metadata like help string, argument parameters.
