### ISSUE TITLE
Firefly fails if path is not specified for a function in the config file

### ISSUE THREAD

**Issue by anandology** [rorodata/firefly#54]
Firefly failed when trying to start it with a config file that does not have `path` field not specified for a function.

The error I got is:

```
Traceback (most recent call last):
  File "/usr/local/bin/firefly", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/firefly/main.py", line 80, in main
    functions, token = parse_config_data(parse_config_file(args.config_file))
  File "/usr/local/lib/python3.6/site-packages/firefly/main.py", line 57, in parse_config_data
    for name, f in config_dict["functions"].items()]
  File "/usr/local/lib/python3.6/site-packages/firefly/main.py", line 57, in <listcomp>
    for name, f in config_dict["functions"].items()]
KeyError: 'path'
```

And the config file is:

```
version: 1.0
functions:
    login:
        path: "/login"
        function: "roro_server.app.login"
    run:
        function: roro_server.app.run
```

Ideally, it should take infer the path from the function name as it does with the command-line arguments. Even otherwise, it should show a nice error message instead of crashing with a cryptic message like this.

**Comment by palnabarun** [comment]
What if it takes the function name as a path resource if path is not explicitly provided? @anandology

**Comment by anandology** [comment]
sounds good. You may have to add a `/` before the function name to get the path.

**Comment by anandology** [comment]
Done.
