### ISSUE TITLE
Issue in installation

### ISSUE THREAD

**Issue by divyam3897** [rorodata/firefly#66]
On doing pip install firefly-python I get:
```
  Could not find a version that satisfies the requirement firefly-python (from versions: )
No matching distribution found for firefly-python
```
I am using arch linux with python 3.6.2

**Comment by anandology** [comment]
please share what you've tried to install and the complete log.

**Comment by divyam3897** [comment]
Closing this, was a problem on my end, fixed it with some tweaks. Thanks.
