### ISSUE TITLE
Add the ability to find all the available functions served by a firefly service

### ISSUE THREAD

**Issue by anandology** [rorodata/firefly#8]
The user should be able to find the functions available in a firefly service. Right now a server supports only one function, but that is going to change soon. 

So, we need to identify the right way to expose the list of functions. It could either be on `/` or some other endpoint like `/_list`. Look at the other RPC implementations and see how they work. We don't have to follow them, but that would give a good idea. It would be better to provide the docstring and argument names along with the function listing.

Please discuss the plan here before implementing.

**Comment by palnabarun** [comment]
I can think of these endpoints-
1. / > for the listing of functions and small help snippets
2. /<function_name> > for function endpoints
3. /<function_name>/help > for function specific help text.

Or this can also be done
1. /help > Same as 1 above
2. /help/<function_name> > Same as 3 above
3. /<function_name> > Same as 2 above

**Comment by anandology** [comment]
Here is my suggestion to start with. Make the help part of the function listing.
```
GET /

{
    "app": "firefly",
    "version": "0.1.0",
    "functions": {
        "func1": {
           "path": "/func1",
           "doc": "docstring of func1"
        },
        "func2": {
           "path": "/func2",
           "doc": "docstring of func2"
        }
    }
}
```

No individual help for functions.
