### ISSUE TITLE
Implement a firefly client interface

### ISSUE THREAD

**Issue by anandology** [rorodata/firefly#9]
It should be possible to invoke remote functions exposed by any firefly service as if they are local.

Assuming a firefly service for `fib` is running on `http://127.0.0.1:8000`, the user should be able to do:

```
>>> import firefly
>>> fib = firefly.Client("http://127.0.0.1:8000")
>>> fib.fib(10)
89
>>> help(fib.fib)
fib(n):
    Computes n'th fibbonacci number.
```

**Comment by palnabarun** [comment]
This looks good for now. I couldn't think of any better schema.
I am a bit fuzzy on the implementation though.
